version: '3.8'

services:
  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:6.0-d2
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
      - "1990:1990"
      - "8088:8088"
      - "8000:8000/udp"
    environment:
      - CANDIDATE=192.168.1.9
    tty: true

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /root/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "--appendonly", "yes" ]

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - D:\Docker-vm\folder\minio\data:/data
      - D:\Docker-vm\folder\minio\config:/root/.minio
    command: server /data --console-address ":9090" --address ":9000"

  nacos:
    image: nacos/nacos-server:v2.2.1
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
    tty: true

  rabbitmq:
    image: rabbitmq
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    tty: true
    command: rabbitmq-server

networks:
  default:
    driver: bridge

  