spring:
  cloud:
    gateway:
      routes:

        - id: im-connect # 长连接服务  TODO 暂时放在这里,后面分离websocket网关时 请移除
          uri: lb:ws://im-connect
          predicates:
            - Path=/im/**

        - id: im-service # 业务服务
          uri: lb://im-service
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1

        - id: im-auth # 认证服务
          uri: lb://im-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: im-leaf # 分布式ID服务
          uri: lb://im-leaf
          predicates:
            - Path=/gen/**

        - id: im-platform # 平台服务
          uri: lb://im-platform
          predicates:
            - Path=/plat/**
          filters:
            - StripPrefix=1

        - id: im-file # 文件服务
          uri: lb://im-file
          predicates:
            - Path=/upload/**
          filters:
            - StripPrefix=1

        - id: im-wallet # 钱包服务
          uri: lb://im-wallet
          predicates:
            - Path=/wallet/**
          filters:
            - StripPrefix=1
