spring:
  cloud:
    gateway:
      routes:
        - id: im-connect # 长连接服务
          uri: lb:ws://im-connect
          predicates:
            - Path=/im/**

        - id: im-meet # 会议服务
          uri: lb:ws://im-meet
          predicates:
            - Path=/meet/**
