server:
  compression:
    # http响应的gzip压缩
    enabled: true
    # 压缩所需的最小长度，响应长度大于等于该值就会压缩，默认2KB
    min-response-size: 2048
    # 需要压缩的响应的Content-type
    mime-types:
      - image/png
      - image/jpeg
      - image/jpg
      - text/html
      - application/javascript
      - text/css
      - application/octet-stream
      - application/json

spring:
  jackson:
    time-zone: UTC
  banner:
    location: classpath:banner.txt
  threads:
    virtual:
      enabled: true  # 开启虚拟线程
  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/im-core
    username: postgres # 数据库账号
    password: 123456 # 数据库密码
  jpa:
    hibernate:
      #     更新或者创建数据表结构
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          max-active: 100
          max-wait: -1ms

# TODO: log settings
logging:
  config: classpath:logback-plus.xml  #日志配置文件，会在当前项目下去找日志配置文件
  level:
    com.xy.*.mapper: debug
    com.xy.*: debug
    org.springframework: warn
