// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: im_connect_message.proto
// Protobuf Java Version: 4.29.5

package com.xy.connect.domain.proto;

public final class ImConnectProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_connect_IMConnectMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_im_connect_IMConnectMessage_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_im_connect_IMConnectMessage_MetadataEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_im_connect_IMConnectMessage_MetadataEntry_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 5,
                /* suffix= */ "",
                ImConnectProto.class.getName());
    }

    static {
        String[] descriptorData = {
                "\n\030im_connect_message.proto\022\nim.connect\032\031" +
                        "google/protobuf/any.proto\"\220\002\n\020IMConnectM" +
                        "essage\022\014\n\004code\030\001 \001(\005\022\r\n\005token\030\002 \001(\t\022\"\n\004d" +
                        "ata\030\003 \001(\0132\024.google.protobuf.Any\022<\n\010metad" +
                        "ata\030\004 \003(\0132*.im.connect.IMConnectMessage." +
                        "MetadataEntry\022\022\n\nrequest_id\030\005 \001(\t\022\021\n\ttim" +
                        "estamp\030\006 \001(\003\022\021\n\tclient_ip\030\007 \001(\t\022\022\n\nuser_" +
                        "agent\030\010 \001(\t\032/\n\rMetadataEntry\022\013\n\003key\030\001 \001(" +
                        "\t\022\r\n\005value\030\002 \001(\t:\0028\001B-\n\033com.xy.connect.d" +
                        "omain.protoB\016ImConnectProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        });
        internal_static_im_connect_IMConnectMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_im_connect_IMConnectMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_im_connect_IMConnectMessage_descriptor,
                new String[]{"Code", "Token", "Data", "Metadata", "RequestId", "Timestamp", "ClientIp", "UserAgent",});
        internal_static_im_connect_IMConnectMessage_MetadataEntry_descriptor =
                internal_static_im_connect_IMConnectMessage_descriptor.getNestedTypes().get(0);
        internal_static_im_connect_IMConnectMessage_MetadataEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_im_connect_IMConnectMessage_MetadataEntry_descriptor,
                new String[]{"Key", "Value",});
        descriptor.resolveAllFeaturesImmutable();
        com.google.protobuf.AnyProto.getDescriptor();
    }

    private ImConnectProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface IMConnectMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:im.connect.IMConnectMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        int getCode();

        /**
         * <code>string token = 2;</code>
         *
         * @return The token.
         */
        String getToken();

        /**
         * <code>string token = 2;</code>
         *
         * @return The bytes for token.
         */
        com.google.protobuf.ByteString
        getTokenBytes();

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        boolean hasData();

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         *
         * @return The data.
         */
        com.google.protobuf.Any getData();

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        int getMetadataCount();

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        boolean containsMetadata(
                String key);

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @Deprecated
        java.util.Map<String, String>
        getMetadata();

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        java.util.Map<String, String>
        getMetadataMap();

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        /* nullable */
        String getMetadataOrDefault(
                String key,
                /* nullable */
                String defaultValue);

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        String getMetadataOrThrow(
                String key);

        /**
         * <pre>
         * 请求 ID（链路追踪）
         * </pre>
         *
         * <code>string request_id = 5;</code>
         *
         * @return The requestId.
         */
        String getRequestId();

        /**
         * <pre>
         * 请求 ID（链路追踪）
         * </pre>
         *
         * <code>string request_id = 5;</code>
         *
         * @return The bytes for requestId.
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <pre>
         * 时间戳（毫秒）
         * </pre>
         *
         * <code>int64 timestamp = 6;</code>
         *
         * @return The timestamp.
         */
        long getTimestamp();

        /**
         * <pre>
         * 客户端信息
         * </pre>
         *
         * <code>string client_ip = 7;</code>
         *
         * @return The clientIp.
         */
        String getClientIp();

        /**
         * <pre>
         * 客户端信息
         * </pre>
         *
         * <code>string client_ip = 7;</code>
         *
         * @return The bytes for clientIp.
         */
        com.google.protobuf.ByteString
        getClientIpBytes();

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The userAgent.
         */
        String getUserAgent();

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The bytes for userAgent.
         */
        com.google.protobuf.ByteString
        getUserAgentBytes();
    }

    /**
     * Protobuf type {@code im.connect.IMConnectMessage}
     */
    public static final class IMConnectMessage extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:im.connect.IMConnectMessage)
            IMConnectMessageOrBuilder {
        public static final int CODE_FIELD_NUMBER = 1;
        public static final int TOKEN_FIELD_NUMBER = 2;
        public static final int DATA_FIELD_NUMBER = 3;
        public static final int METADATA_FIELD_NUMBER = 4;
        public static final int REQUEST_ID_FIELD_NUMBER = 5;
        public static final int TIMESTAMP_FIELD_NUMBER = 6;
        public static final int CLIENT_IP_FIELD_NUMBER = 7;
        public static final int USER_AGENT_FIELD_NUMBER = 8;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:im.connect.IMConnectMessage)
        private static final IMConnectMessage DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<IMConnectMessage>
                PARSER = new com.google.protobuf.AbstractParser<IMConnectMessage>() {
            @Override
            public IMConnectMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 29,
                    /* patch= */ 5,
                    /* suffix= */ "",
                    IMConnectMessage.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new IMConnectMessage();
        }

        private int bitField0_;
        private int code_ = 0;
        @SuppressWarnings("serial")
        private volatile Object token_ = "";
        private com.google.protobuf.Any data_;
        @SuppressWarnings("serial")
        private com.google.protobuf.MapField<
                String, String> metadata_;
        @SuppressWarnings("serial")
        private volatile Object requestId_ = "";
        private long timestamp_ = 0L;
        @SuppressWarnings("serial")
        private volatile Object clientIp_ = "";
        @SuppressWarnings("serial")
        private volatile Object userAgent_ = "";
        private byte memoizedIsInitialized = -1;

        // Use IMConnectMessage.newBuilder() to construct.
        private IMConnectMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private IMConnectMessage() {
            token_ = "";
            requestId_ = "";
            clientIp_ = "";
            userAgent_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ImConnectProto.internal_static_im_connect_IMConnectMessage_descriptor;
        }

        public static IMConnectMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IMConnectMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IMConnectMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IMConnectMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IMConnectMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IMConnectMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IMConnectMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static IMConnectMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static IMConnectMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static IMConnectMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static IMConnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static IMConnectMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(IMConnectMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static IMConnectMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<IMConnectMessage> parser() {
            return PARSER;
        }

        @SuppressWarnings({"rawtypes"})
        @Override
        protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
                int number) {
            switch (number) {
                case 4:
                    return internalGetMetadata();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ImConnectProto.internal_static_im_connect_IMConnectMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IMConnectMessage.class, Builder.class);
        }

        /**
         * <code>int32 code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public int getCode() {
            return code_;
        }

        /**
         * <code>string token = 2;</code>
         *
         * @return The token.
         */
        @Override
        public String getToken() {
            Object ref = token_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                token_ = s;
                return s;
            }
        }

        /**
         * <code>string token = 2;</code>
         *
         * @return The bytes for token.
         */
        @Override
        public com.google.protobuf.ByteString
        getTokenBytes() {
            Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         *
         * @return Whether the data field is set.
         */
        @Override
        public boolean hasData() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         *
         * @return The data.
         */
        @Override
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <pre>
         * 3. 泛型 payload（推荐方式：Any）
         * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
         * </pre>
         *
         * <code>.google.protobuf.Any data = 3;</code>
         */
        @Override
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        private com.google.protobuf.MapField<String, String>
        internalGetMetadata() {
            if (metadata_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MetadataDefaultEntryHolder.defaultEntry);
            }
            return metadata_;
        }

        public int getMetadataCount() {
            return internalGetMetadata().getMap().size();
        }

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        @Override
        public boolean containsMetadata(
                String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            return internalGetMetadata().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, String> getMetadata() {
            return getMetadataMap();
        }

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        @Override
        public java.util.Map<String, String> getMetadataMap() {
            return internalGetMetadata().getMap();
        }

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        @Override
        public /* nullable */
        String getMetadataOrDefault(
                String key,
                /* nullable */
                String defaultValue) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<String, String> map =
                    internalGetMetadata().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <pre>
         * 可选元数据（路由/版本/平台等）
         * </pre>
         *
         * <code>map&lt;string, string&gt; metadata = 4;</code>
         */
        @Override
        public String getMetadataOrThrow(
                String key) {
            if (key == null) {
                throw new NullPointerException("map key");
            }
            java.util.Map<String, String> map =
                    internalGetMetadata().getMap();
            if (!map.containsKey(key)) {
                throw new IllegalArgumentException();
            }
            return map.get(key);
        }

        /**
         * <pre>
         * 请求 ID（链路追踪）
         * </pre>
         *
         * <code>string request_id = 5;</code>
         *
         * @return The requestId.
         */
        @Override
        public String getRequestId() {
            Object ref = requestId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestId_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 请求 ID（链路追踪）
         * </pre>
         *
         * <code>string request_id = 5;</code>
         *
         * @return The bytes for requestId.
         */
        @Override
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            Object ref = requestId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 时间戳（毫秒）
         * </pre>
         *
         * <code>int64 timestamp = 6;</code>
         *
         * @return The timestamp.
         */
        @Override
        public long getTimestamp() {
            return timestamp_;
        }

        /**
         * <pre>
         * 客户端信息
         * </pre>
         *
         * <code>string client_ip = 7;</code>
         *
         * @return The clientIp.
         */
        @Override
        public String getClientIp() {
            Object ref = clientIp_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                clientIp_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 客户端信息
         * </pre>
         *
         * <code>string client_ip = 7;</code>
         *
         * @return The bytes for clientIp.
         */
        @Override
        public com.google.protobuf.ByteString
        getClientIpBytes() {
            Object ref = clientIp_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                clientIp_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The userAgent.
         */
        @Override
        public String getUserAgent() {
            Object ref = userAgent_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                userAgent_ = s;
                return s;
            }
        }

        /**
         * <code>string user_agent = 8;</code>
         *
         * @return The bytes for userAgent.
         */
        @Override
        public com.google.protobuf.ByteString
        getUserAgentBytes() {
            Object ref = userAgent_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userAgent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (code_ != 0) {
                output.writeInt32(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, token_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(3, getData());
            }
            com.google.protobuf.GeneratedMessage
                    .serializeStringMapTo(
                            output,
                            internalGetMetadata(),
                            MetadataDefaultEntryHolder.defaultEntry,
                            4);
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 5, requestId_);
            }
            if (timestamp_ != 0L) {
                output.writeInt64(6, timestamp_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientIp_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 7, clientIp_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userAgent_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 8, userAgent_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (code_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, code_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, token_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getData());
            }
            for (java.util.Map.Entry<String, String> entry
                    : internalGetMetadata().getMap().entrySet()) {
                com.google.protobuf.MapEntry<String, String>
                        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, metadata__);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(5, requestId_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(6, timestamp_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientIp_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(7, clientIp_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userAgent_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(8, userAgent_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof IMConnectMessage)) {
                return super.equals(obj);
            }
            IMConnectMessage other = (IMConnectMessage) obj;

            if (getCode()
                    != other.getCode()) return false;
            if (!getToken()
                    .equals(other.getToken())) return false;
            if (hasData() != other.hasData()) return false;
            if (hasData()) {
                if (!getData()
                        .equals(other.getData())) return false;
            }
            if (!internalGetMetadata().equals(
                    other.internalGetMetadata())) return false;
            if (!getRequestId()
                    .equals(other.getRequestId())) return false;
            if (getTimestamp()
                    != other.getTimestamp()) return false;
            if (!getClientIp()
                    .equals(other.getClientIp())) return false;
            if (!getUserAgent()
                    .equals(other.getUserAgent())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode();
            hash = (37 * hash) + TOKEN_FIELD_NUMBER;
            hash = (53 * hash) + getToken().hashCode();
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            if (!internalGetMetadata().getMap().isEmpty()) {
                hash = (37 * hash) + METADATA_FIELD_NUMBER;
                hash = (53 * hash) + internalGetMetadata().hashCode();
            }
            hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId().hashCode();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (37 * hash) + CLIENT_IP_FIELD_NUMBER;
            hash = (53 * hash) + getClientIp().hashCode();
            hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
            hash = (53 * hash) + getUserAgent().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<IMConnectMessage> getParserForType() {
            return PARSER;
        }

        @Override
        public IMConnectMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class MetadataDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    String, String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<String, String>newDefaultInstance(
                                    ImConnectProto.internal_static_im_connect_IMConnectMessage_MetadataEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }

        /**
         * Protobuf type {@code im.connect.IMConnectMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:im.connect.IMConnectMessage)
                IMConnectMessageOrBuilder {
            private int bitField0_;
            private int code_;
            private Object token_ = "";
            private com.google.protobuf.Any data_;
            private com.google.protobuf.SingleFieldBuilder<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
            private com.google.protobuf.MapField<
                    String, String> metadata_;
            private Object requestId_ = "";
            private long timestamp_;
            private Object clientIp_ = "";
            private Object userAgent_ = "";

            // Construct using com.xy.connect.domain.proto.ImConnectProto.IMConnectMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ImConnectProto.internal_static_im_connect_IMConnectMessage_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMetadata();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
                    int number) {
                switch (number) {
                    case 4:
                        return internalGetMutableMetadata();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ImConnectProto.internal_static_im_connect_IMConnectMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IMConnectMessage.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getDataFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = 0;
                token_ = "";
                data_ = null;
                if (dataBuilder_ != null) {
                    dataBuilder_.dispose();
                    dataBuilder_ = null;
                }
                internalGetMutableMetadata().clear();
                requestId_ = "";
                timestamp_ = 0L;
                clientIp_ = "";
                userAgent_ = "";
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ImConnectProto.internal_static_im_connect_IMConnectMessage_descriptor;
            }

            @Override
            public IMConnectMessage getDefaultInstanceForType() {
                return IMConnectMessage.getDefaultInstance();
            }

            @Override
            public IMConnectMessage build() {
                IMConnectMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public IMConnectMessage buildPartial() {
                IMConnectMessage result = new IMConnectMessage(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(IMConnectMessage result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.token_ = token_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.data_ = dataBuilder_ == null
                            ? data_
                            : dataBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.metadata_ = internalGetMetadata();
                    result.metadata_.makeImmutable();
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.requestId_ = requestId_;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.timestamp_ = timestamp_;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.clientIp_ = clientIp_;
                }
                if (((from_bitField0_ & 0x00000080) != 0)) {
                    result.userAgent_ = userAgent_;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof IMConnectMessage) {
                    return mergeFrom((IMConnectMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(IMConnectMessage other) {
                if (other == IMConnectMessage.getDefaultInstance()) return this;
                if (other.getCode() != 0) {
                    setCode(other.getCode());
                }
                if (!other.getToken().isEmpty()) {
                    token_ = other.token_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                internalGetMutableMetadata().mergeFrom(
                        other.internalGetMetadata());
                bitField0_ |= 0x00000008;
                if (!other.getRequestId().isEmpty()) {
                    requestId_ = other.requestId_;
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                if (!other.getClientIp().isEmpty()) {
                    clientIp_ = other.clientIp_;
                    bitField0_ |= 0x00000040;
                    onChanged();
                }
                if (!other.getUserAgent().isEmpty()) {
                    userAgent_ = other.userAgent_;
                    bitField0_ |= 0x00000080;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                code_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                token_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                input.readMessage(
                                        getDataFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                com.google.protobuf.MapEntry<String, String>
                                        metadata__ = input.readMessage(
                                        MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                                internalGetMutableMetadata().getMutableMap().put(
                                        metadata__.getKey(), metadata__.getValue());
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                requestId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 48: {
                                timestamp_ = input.readInt64();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 48
                            case 58: {
                                clientIp_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 58
                            case 66: {
                                userAgent_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000080;
                                break;
                            } // case 66
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @return The code.
             */
            @Override
            public int getCode() {
                return code_;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(int value) {

                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string token = 2;</code>
             *
             * @return The token.
             */
            public String getToken() {
                Object ref = token_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    token_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string token = 2;</code>
             *
             * @param value The token to set.
             * @return This builder for chaining.
             */
            public Builder setToken(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                token_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string token = 2;</code>
             *
             * @return The bytes for token.
             */
            public com.google.protobuf.ByteString
            getTokenBytes() {
                Object ref = token_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    token_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string token = 2;</code>
             *
             * @param value The bytes for token to set.
             * @return This builder for chaining.
             */
            public Builder setTokenBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                token_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>string token = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearToken() {
                token_ = getDefaultInstance().getToken();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             *
             * @return Whether the data field is set.
             */
            public boolean hasData() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             *
             * @return The data.
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                } else {
                    dataBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder setData(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) != 0) &&
                            data_ != null &&
                            data_ != com.google.protobuf.Any.getDefaultInstance()) {
                        getDataBuilder().mergeFrom(value);
                    } else {
                        data_ = value;
                    }
                } else {
                    dataBuilder_.mergeFrom(value);
                }
                if (data_ != null) {
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                return this;
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000004);
                data_ = null;
                if (dataBuilder_ != null) {
                    dataBuilder_.dispose();
                    dataBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {
                bitField0_ |= 0x00000004;
                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <pre>
             * 3. 泛型 payload（推荐方式：Any）
             * 任意 protobuf message 都可以被 pack 成一个 Any 放到这里
             * </pre>
             *
             * <code>.google.protobuf.Any data = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMetadata() {
                if (metadata_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            MetadataDefaultEntryHolder.defaultEntry);
                }
                return metadata_;
            }

            private com.google.protobuf.MapField<String, String>
            internalGetMutableMetadata() {
                if (metadata_ == null) {
                    metadata_ = com.google.protobuf.MapField.newMapField(
                            MetadataDefaultEntryHolder.defaultEntry);
                }
                if (!metadata_.isMutable()) {
                    metadata_ = metadata_.copy();
                }
                bitField0_ |= 0x00000008;
                onChanged();
                return metadata_;
            }

            public int getMetadataCount() {
                return internalGetMetadata().getMap().size();
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            @Override
            public boolean containsMetadata(
                    String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                return internalGetMetadata().getMap().containsKey(key);
            }

            /**
             * Use {@link #getMetadataMap()} instead.
             */
            @Override
            @Deprecated
            public java.util.Map<String, String> getMetadata() {
                return getMetadataMap();
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            @Override
            public java.util.Map<String, String> getMetadataMap() {
                return internalGetMetadata().getMap();
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            @Override
            public /* nullable */
            String getMetadataOrDefault(
                    String key,
                    /* nullable */
                    String defaultValue) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<String, String> map =
                        internalGetMetadata().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            @Override
            public String getMetadataOrThrow(
                    String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                java.util.Map<String, String> map =
                        internalGetMetadata().getMap();
                if (!map.containsKey(key)) {
                    throw new IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearMetadata() {
                bitField0_ = (bitField0_ & ~0x00000008);
                internalGetMutableMetadata().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            public Builder removeMetadata(
                    String key) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                internalGetMutableMetadata().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @Deprecated
            public java.util.Map<String, String>
            getMutableMetadata() {
                bitField0_ |= 0x00000008;
                return internalGetMutableMetadata().getMutableMap();
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            public Builder putMetadata(
                    String key,
                    String value) {
                if (key == null) {
                    throw new NullPointerException("map key");
                }
                if (value == null) {
                    throw new NullPointerException("map value");
                }
                internalGetMutableMetadata().getMutableMap()
                        .put(key, value);
                bitField0_ |= 0x00000008;
                return this;
            }

            /**
             * <pre>
             * 可选元数据（路由/版本/平台等）
             * </pre>
             *
             * <code>map&lt;string, string&gt; metadata = 4;</code>
             */
            public Builder putAllMetadata(
                    java.util.Map<String, String> values) {
                internalGetMutableMetadata().getMutableMap()
                        .putAll(values);
                bitField0_ |= 0x00000008;
                return this;
            }

            /**
             * <pre>
             * 请求 ID（链路追踪）
             * </pre>
             *
             * <code>string request_id = 5;</code>
             *
             * @return The requestId.
             */
            public String getRequestId() {
                Object ref = requestId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    requestId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 请求 ID（链路追踪）
             * </pre>
             *
             * <code>string request_id = 5;</code>
             *
             * @param value The requestId to set.
             * @return This builder for chaining.
             */
            public Builder setRequestId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                requestId_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求 ID（链路追踪）
             * </pre>
             *
             * <code>string request_id = 5;</code>
             *
             * @return The bytes for requestId.
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 请求 ID（链路追踪）
             * </pre>
             *
             * <code>string request_id = 5;</code>
             *
             * @param value The bytes for requestId to set.
             * @return This builder for chaining.
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                requestId_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 请求 ID（链路追踪）
             * </pre>
             *
             * <code>string request_id = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRequestId() {
                requestId_ = getDefaultInstance().getRequestId();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 时间戳（毫秒）
             * </pre>
             *
             * <code>int64 timestamp = 6;</code>
             *
             * @return The timestamp.
             */
            @Override
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <pre>
             * 时间戳（毫秒）
             * </pre>
             *
             * <code>int64 timestamp = 6;</code>
             *
             * @param value The timestamp to set.
             * @return This builder for chaining.
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 时间戳（毫秒）
             * </pre>
             *
             * <code>int64 timestamp = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000020);
                timestamp_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 客户端信息
             * </pre>
             *
             * <code>string client_ip = 7;</code>
             *
             * @return The clientIp.
             */
            public String getClientIp() {
                Object ref = clientIp_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    clientIp_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <pre>
             * 客户端信息
             * </pre>
             *
             * <code>string client_ip = 7;</code>
             *
             * @param value The clientIp to set.
             * @return This builder for chaining.
             */
            public Builder setClientIp(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                clientIp_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 客户端信息
             * </pre>
             *
             * <code>string client_ip = 7;</code>
             *
             * @return The bytes for clientIp.
             */
            public com.google.protobuf.ByteString
            getClientIpBytes() {
                Object ref = clientIp_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    clientIp_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 客户端信息
             * </pre>
             *
             * <code>string client_ip = 7;</code>
             *
             * @param value The bytes for clientIp to set.
             * @return This builder for chaining.
             */
            public Builder setClientIpBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                clientIp_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 客户端信息
             * </pre>
             *
             * <code>string client_ip = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearClientIp() {
                clientIp_ = getDefaultInstance().getClientIp();
                bitField0_ = (bitField0_ & ~0x00000040);
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return The userAgent.
             */
            public String getUserAgent() {
                Object ref = userAgent_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    userAgent_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @param value The userAgent to set.
             * @return This builder for chaining.
             */
            public Builder setUserAgent(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                userAgent_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return The bytes for userAgent.
             */
            public com.google.protobuf.ByteString
            getUserAgentBytes() {
                Object ref = userAgent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userAgent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @param value The bytes for userAgent to set.
             * @return This builder for chaining.
             */
            public Builder setUserAgentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                userAgent_ = value;
                bitField0_ |= 0x00000080;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 8;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUserAgent() {
                userAgent_ = getDefaultInstance().getUserAgent();
                bitField0_ = (bitField0_ & ~0x00000080);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:im.connect.IMConnectMessage)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
