// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generic.proto

package com.xy.grpc.core.generic;

/**
 * Protobuf type {@code generic.GenericRequest}
 */
public final class GenericRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:generic.GenericRequest)
        GenericRequestOrBuilder {
    public static final int URL_FIELD_NUMBER = 1;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    public static final int METADATA_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:generic.GenericRequest)
    private static final com.xy.grpc.core.generic.GenericRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<GenericRequest>
            PARSER = new com.google.protobuf.AbstractParser<GenericRequest>() {
        @java.lang.Override
        public GenericRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new GenericRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.xy.grpc.core.generic.GenericRequest();
    }

    private volatile java.lang.Object url_;
    private com.google.protobuf.ByteString payload_;
    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> metadata_;
    private byte memoizedIsInitialized = -1;

    // Use GenericRequest.newBuilder() to construct.
    private GenericRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GenericRequest() {
        url_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    private GenericRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        url_ = s;
                        break;
                    }
                    case 18: {

                        payload_ = input.readBytes();
                        break;
                    }
                    case 26: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            metadata_ = com.google.protobuf.MapField.newMapField(
                                    MetadataDefaultEntryHolder.defaultEntry);
                            mutable_bitField0_ |= 0x00000001;
                        }
                        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                metadata__ = input.readMessage(
                                MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                        metadata_.getMutableMap().put(
                                metadata__.getKey(), metadata__.getValue());
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_descriptor;
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.xy.grpc.core.generic.GenericRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.xy.grpc.core.generic.GenericRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.xy.grpc.core.generic.GenericRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<GenericRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new GenericRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
        switch (number) {
            case 3:
                return internalGetMetadata();
            default:
                throw new RuntimeException(
                        "Invalid map field number: " + number);
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.xy.grpc.core.generic.GenericRequest.class, com.xy.grpc.core.generic.GenericRequest.Builder.class);
    }

    /**
     * <code>string url = 1;</code>
     *
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            url_ = s;
            return s;
        }
    }

    /**
     * <code>string url = 1;</code>
     *
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            url_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <code>bytes payload = 2;</code>
     *
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
        return payload_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetadata() {
        if (metadata_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
    }

    public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        return internalGetMetadata().getMap().containsKey(key);
    }

    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
        return getMetadataMap();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
        return internalGetMetadata().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetadataOrThrow(
            java.lang.String key) {
        if (key == null) {
            throw new java.lang.NullPointerException();
        }
        java.util.Map<java.lang.String, java.lang.String> map =
                internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getUrlBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
        }
        if (!payload_.isEmpty()) {
            output.writeBytes(2, payload_);
        }
        com.google.protobuf.GeneratedMessageV3
                .serializeStringMapTo(
                        output,
                        internalGetMetadata(),
                        MetadataDefaultEntryHolder.defaultEntry,
                        3);
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUrlBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
        }
        if (!payload_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, payload_);
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                : internalGetMetadata().getMap().entrySet()) {
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                    metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
                    .setKey(entry.getKey())
                    .setValue(entry.getValue())
                    .build();
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, metadata__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.xy.grpc.core.generic.GenericRequest)) {
            return super.equals(obj);
        }
        com.xy.grpc.core.generic.GenericRequest other = (com.xy.grpc.core.generic.GenericRequest) obj;

        if (!getUrl()
                .equals(other.getUrl())) return false;
        if (!getPayload()
                .equals(other.getPayload())) return false;
        if (!internalGetMetadata().equals(
                other.internalGetMetadata())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getUrl().hashCode();
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
        if (!internalGetMetadata().getMap().isEmpty()) {
            hash = (37 * hash) + METADATA_FIELD_NUMBER;
            hash = (53 * hash) + internalGetMetadata().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenericRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.xy.grpc.core.generic.GenericRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    private static final class MetadataDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
                java.lang.String, java.lang.String> defaultEntry =
                com.google.protobuf.MapEntry
                        .<java.lang.String, java.lang.String>newDefaultInstance(
                                com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_MetadataEntry_descriptor,
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "",
                                com.google.protobuf.WireFormat.FieldType.STRING,
                                "");
    }

    /**
     * Protobuf type {@code generic.GenericRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:generic.GenericRequest)
            com.xy.grpc.core.generic.GenericRequestOrBuilder {
        private int bitField0_;
        private java.lang.Object url_ = "";
        private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> metadata_;

        // Construct using com.xy.grpc.core.generic.GenericRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 3:
                    return internalGetMetadata();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
                int number) {
            switch (number) {
                case 3:
                    return internalGetMutableMetadata();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.xy.grpc.core.generic.GenericRequest.class, com.xy.grpc.core.generic.GenericRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            url_ = "";

            payload_ = com.google.protobuf.ByteString.EMPTY;

            internalGetMutableMetadata().clear();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.xy.grpc.core.generic.GenericProto.internal_static_generic_GenericRequest_descriptor;
        }

        @java.lang.Override
        public com.xy.grpc.core.generic.GenericRequest getDefaultInstanceForType() {
            return com.xy.grpc.core.generic.GenericRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.xy.grpc.core.generic.GenericRequest build() {
            com.xy.grpc.core.generic.GenericRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.xy.grpc.core.generic.GenericRequest buildPartial() {
            com.xy.grpc.core.generic.GenericRequest result = new com.xy.grpc.core.generic.GenericRequest(this);
            int from_bitField0_ = bitField0_;
            result.url_ = url_;
            result.payload_ = payload_;
            result.metadata_ = internalGetMetadata();
            result.metadata_.makeImmutable();
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.xy.grpc.core.generic.GenericRequest) {
                return mergeFrom((com.xy.grpc.core.generic.GenericRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.xy.grpc.core.generic.GenericRequest other) {
            if (other == com.xy.grpc.core.generic.GenericRequest.getDefaultInstance()) return this;
            if (!other.getUrl().isEmpty()) {
                url_ = other.url_;
                onChanged();
            }
            if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
                setPayload(other.getPayload());
            }
            internalGetMutableMetadata().mergeFrom(
                    other.internalGetMetadata());
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.xy.grpc.core.generic.GenericRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.xy.grpc.core.generic.GenericRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>string url = 1;</code>
         *
         * @return The url.
         */
        public java.lang.String getUrl() {
            java.lang.Object ref = url_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                url_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string url = 1;</code>
         *
         * @param value The url to set.
         * @return This builder for chaining.
         */
        public Builder setUrl(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            url_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string url = 1;</code>
         *
         * @return The bytes for url.
         */
        public com.google.protobuf.ByteString
        getUrlBytes() {
            java.lang.Object ref = url_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                url_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string url = 1;</code>
         *
         * @param value The bytes for url to set.
         * @return This builder for chaining.
         */
        public Builder setUrlBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            url_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string url = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUrl() {

            url_ = getDefaultInstance().getUrl();
            onChanged();
            return this;
        }

        /**
         * <code>bytes payload = 2;</code>
         *
         * @return The payload.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPayload() {
            return payload_;
        }

        /**
         * <code>bytes payload = 2;</code>
         *
         * @param value The payload to set.
         * @return This builder for chaining.
         */
        public Builder setPayload(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            payload_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes payload = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPayload() {

            payload_ = getDefaultInstance().getPayload();
            onChanged();
            return this;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
            if (metadata_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        MetadataDefaultEntryHolder.defaultEntry);
            }
            return metadata_;
        }

        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadata() {
            onChanged();
            ;
            if (metadata_ == null) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                        MetadataDefaultEntryHolder.defaultEntry);
            }
            if (!metadata_.isMutable()) {
                metadata_ = metadata_.copy();
            }
            return metadata_;
        }

        public int getMetadataCount() {
            return internalGetMetadata().getMap().size();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */

        @java.lang.Override
        public boolean containsMetadata(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetMetadata().getMap().containsKey(key);
        }

        /**
         * Use {@link #getMetadataMap()} instead.
         */
        @java.lang.Override
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
            return getMetadataMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */
        @java.lang.Override

        public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
            return internalGetMetadata().getMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMetadata().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */
        @java.lang.Override

        public java.lang.String getMetadataOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetMetadata().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        public Builder clearMetadata() {
            internalGetMutableMetadata().getMutableMap()
                    .clear();
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */

        public Builder removeMetadata(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap()
                    .remove(key);
            return this;
        }

        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadata() {
            return internalGetMutableMetadata().getMutableMap();
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */
        public Builder putMetadata(
                java.lang.String key,
                java.lang.String value) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            if (value == null) {
                throw new java.lang.NullPointerException();
            }
            internalGetMutableMetadata().getMutableMap()
                    .put(key, value);
            return this;
        }

        /**
         * <code>map&lt;string, string&gt; metadata = 3;</code>
         */

        public Builder putAllMetadata(
                java.util.Map<java.lang.String, java.lang.String> values) {
            internalGetMutableMetadata().getMutableMap()
                    .putAll(values);
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:generic.GenericRequest)
    }

}

